[package]
name = "WebScrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
minreq = { version = "2.11.0", features = ["punycode"] }
reqwest = "0.12.12"
tokio = { version = "1", features = ["full"] }
